export type DynastyTeam = {
  id: string;
  dynasty_id: string;
  base_team_id: string;
  conference_id: string;
  is_detailed_tracking: boolean;
  year: number;
  is_custom: boolean;
  custom_name: string | null;
  custom_mascot: string | null;
  offensive_scheme: string;
  defensive_scheme: string;
  team_overall: number;
  offense_overall: number;
  defense_overall: number;
  primary_color: string;
  secondary_color: string;
  program_prestige: number;
  championship_contender: string;
  program_tradition: string;
  campus_lifestyle: string;
  stadium_atmosphere: string;
  pro_potential: string;
  brand_exposure: string;
  academic_pressure: string;
  conference_prestige: string;
  coach_prestige: string;
  total_bowl_games: number;
  bowl_game_record: string;
  bowl_game_record_percentage: number;
  total_conference_championships: number;
  total_national_titles: number;
  last_year_record: string;
  last_year_record_percentage: number;
  all_time_record: string;
  all_time_record_percentage: number;
  total_all_americans: number;
  total_heisman_winners: number;
  total_draft_picks: number;
  ap_poll_rank: number | null;
  weeks_in_poll: number;
  blue_blood_score: number;
  blue_blood_rank: number;
  blue_blood_tier: string;
  is_user_team: boolean;
  created_at: string;
  school_name: string;
  nickname: string;
  city: string;
  state: string;
  logo: string;
  conference: string;
};
